// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-4fkVSdneUKt7HLCHwnR72SZE_xl9Pyk',
    appId: '1:947865622828:web:2ac68f9160ab8be49a3489',
    messagingSenderId: '947865622828',
    projectId: 'flutter-car-app-3e947',
    authDomain: 'flutter-car-app-3e947.firebaseapp.com',
    databaseURL: 'https://flutter-car-app-3e947-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-car-app-3e947.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH5trylgxuqP4KL9BK5KbS7-NEGCpMrWg',
    appId: '1:947865622828:android:57c0c8d4810777039a3489',
    messagingSenderId: '947865622828',
    projectId: 'flutter-car-app-3e947',
    databaseURL: 'https://flutter-car-app-3e947-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-car-app-3e947.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzC9Gsw5JNFFDtaIbr9wVDF9vKtzppCNU',
    appId: '1:947865622828:ios:e4437e6aa112b61d9a3489',
    messagingSenderId: '947865622828',
    projectId: 'flutter-car-app-3e947',
    databaseURL: 'https://flutter-car-app-3e947-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-car-app-3e947.appspot.com',
    iosBundleId: 'com.example.flutterappcar.flutterAppCar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzC9Gsw5JNFFDtaIbr9wVDF9vKtzppCNU',
    appId: '1:947865622828:ios:373aeb8783546cfd9a3489',
    messagingSenderId: '947865622828',
    projectId: 'flutter-car-app-3e947',
    databaseURL: 'https://flutter-car-app-3e947-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-car-app-3e947.appspot.com',
    iosBundleId: 'com.example.flutterappcar.flutterAppCar.RunnerTests',
  );
}
